config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :artists, controllers: {
    sessions:      'artists/sessions',
    passwords:     'artists/passwords',
    registrations: 'artists/registrations'
  }
  root to: "top#index"
  get "/explanation" => "top#explanation"
  resources :questions, path: "/questions", only: [:show, :new, :create]
  resources :answers, only: [:new, :create]
  resources :artists, param: :hash_id, path: "artists", only: [ :index, :show]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :answers
  belongs_to :prefecture
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :users
  has_many :artists
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :prefecture
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Jpmobile::ViewSelector
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation, :prefecture_id)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation, :header_photo)
    end
  end

end

app/controllers/artists/passwords_controller.rb
class Artists::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/artists/sessions_controller.rb
class Artists::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/artists/unlocks_controller.rb
class Artists::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    artist_ids = Answer.group(:artist_id).order('count_artist_id DESC').count(:artist_id).keys
    @artists = artist_ids.map{ |id| Artist.find(id) }
  end

  def show
    @artist = Artist.find_by(params[:hash_id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @related_questions = @question.category.questions.order(created_at: :desc).page(params[:page]).limit(5)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    unless @question.save
      render :new
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :text, :user_id, :category_id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).limit(5)
    artist_ids = Answer.group(:artist_id).order('count_artist_id DESC').limit(5).count(:artist_id).keys
    @artists = artist_ids.map{ |id| Artist.find(id) }
    @liked_questions = Question.order(want_count: :desc).limit(5)
  end

  def explanation
    render layout: false
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in


  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/quesitons_helper.rb
module QuesitonsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/questions/create.html.slim
.row
  .col-md-8.col-md-offset-2
    .panel.panel-info
      .panel-heading
        h3 投稿完了
      .panel-body
        p.text-center.c-content 投稿が完了しました。美容師からの返信を待ちましょう。また質問の編集もできます。
        .col-md-6.col-md-offset-3
          = link_to("ホーム", root_path, class: "btn btn-info c-btn")
          = link_to("質問の編集", new_question_path, class: "btn btn-info c-btn")
          = link_to("新しい質問", new_question_path, class: "btn btn-info c-btn")

app/views/questions/new.html.slim
= form_for(@question) do |f|
  .row.center-block
    .col-md-8.pull-left
      .row
        .col-md-12
          h2.new-q 質問内容の入力
      .row
        .col-md-10.col-md-offset-1.devision-line
          .col-md-2.col-md-offset-1
            = f.label :タイトル, class: "q-label"
            span.label.label-danger 必須
          .col-md-9
            = f.text_field :title, class: "form-control area-color"
      .row
        .col-md-10.col-md-offset-1.devision-line
          .col-md-2.col-md-offset-1
            = f.label :質問内容, class: "q-label"
            span.label.label-danger 必須
          .col-md-9
            = f.text_area :text, class: "form-control q-area area-color"
      .row
        .col-md-10.col-md-offset-1.devision-line
          .col-md-2.col-md-offset-1
            = f.label :カテゴリー, class: "q-label"
            span.label.label-danger 必須
          .col-md-9
            = f.collection_select :category_id, Category.all, :id, :name, {prompt: "選択してください"}, {class: "form-control"}
      .row
        .col-md-6.col-md-offset-3.mt10
          = f.submit :内容を確認する, class: "btn btn-info fa-2x center-block"
    .col-md-4.pull-right
      .col-md-12
        .faq
          h3.faq_title 美容専門のQAサービスです。
          p.faq_content 髪の専門家である美容師にあなたの疑問や悩みを相談しましょう。
          p
            a.btn.btn-info.btn-lg.center-block もっと詳しく
      .col-md-12
        .login-inv
          h3.login-inv_title
            span.label.label-info 新規登録/ログイン
          p.login-inv_content アカウントを作って、QAで質問しましょう。

app/views/questions/show.html.slim
.row.center-block
  .col-md-8.pull-left
    .row.q-detail
      .col-md-10.col.col-md-offset-2
        h2.q-detail_title
          i(class="fa fa-question-circle-o fa-orange", aria-hidden="true")
          span.q-detail_title--letter #{@question.title}
      .col-md-10.col-md-offset-2.mb10.underline
        i(class="fa fa-check-circle-o fa-lg fa-orange ml10", aria-hidden="true")
        span.q-detail_category #{@question.category.name}
        span.pull-right.q-detail_ac 回答: #{@question.answers.count} 件
        i(class="fa fa-comment fa-lg fa-orange ml10 pull-right", aria-hidden="true")
      .col-md-10.col-md-offset-2.mb10.underline
        .media.mb10
          a.media-left
            .box-2
          .media-body
            h4.media-heading #{@question.user.name} さん
      .col-md-10.col-md-offset-2.underline
        .q-detail_text 質問詳細
        .q-detail_text--content #{@question.text}
    .row.a-detail
      .col-md-10.col-md-offset-2
        i(class="fa fa-comment fa-2x fa-orange ml10", aria-hidden="true")
        span.a-detail_title 回答 #{@answers.count} 件
      - if @answers.present?
        - @answers.each do |answer|
          .col-md-10.col-md-offset-2.a-detail_bg
            .media.mb10
              a.media-left
                .box-2
              .media-body
                h4.media-heading #{answer.artist.last_name} #{answer.artist.first_name} さん
            .a-detail_text
              p.a-detail_text-content #{answer.text}
          - if current_user.?
            .col-md-10.col-md-offset-2
              .login-inv
                h3.login-inv_title
                  = link_to("質問に答える", new_answer_path, class: "label label-info")
                p.login-inv_content アカウントを作って、QAで質問しましょう。
    .row.c-q
      .col-md-10.col.col-md-offset-2
        .panel.panel-info
          .panel-heading 関連度の高い質
          ul.list-group
          - @related_questions.each do |rq|
            li.list-group-item
              .c-q_header
                i(class="fa fa-question-circle-o fa-orange", aria-hidden="true")
                = link_to("#{rq.title}", question_path(rq), class: "c-q_header--title")
              .c-q_body
                p.c-q_body--content #{rq.text}
              .c-q_footer
                i(class="fa fa-comment fa-lg fa-orange ml10", aria-hidden="true")
                span.c-q_footer-count 回答 #{rq.answers.count} 件
  .col-md-4.pull-right
    .col-md-12
      .login-inv
        h3.login-inv_title
          span.label.label-info 新規登録/ログイン
        p.login-inv_content アカウントを作って、QAで質問しましょう。

app/views/top/explanation.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      | Hairabout
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container-fluid
      .row.lp-top
        .col-md-6.col-md-offset-3
          h2.lp-top_title 質問を通じたお客様とのマッチング
        .col-md-6.col-md-offset-3.lp-top_content
          p.lp-top_explation 質問を通じて、髪に悩み・疑問を持つ方と繋がり、質問を通じて、様々な交流をすることができます。
        .col-md-6.col-md-offset-3
          ul.center-block.lists
            li.lp-top_list
              = link_to('会員登録', new_artist_registration_path, class: "btn btn-info fa-3x site-color")
            li.lp-top_list
              = link_to('ログイン', new_artist_session_path, class: "btn btn-info fa-3x site-color")
      .row.lp-middle
        .col-md-6.col-md-offset-3
          h2.lp-middle_title HairAboutの3つの特徴
        .col-md-8.col-md-offset-3
          ul.center-block.lists
            li.center-block.lp-middle_list
              p.lp-middle_list--content アカウント無料作成
            li.center-block.lp-middle_list
              p.lp-middle_list--content 個人でマーケティング
            li.center-block.lp-middle_list
              p.lp-middle_list--content お客様との交流
      .row.lp-bottom
        .col-md-6.col-md-offset-3
          h2.lp-bottom_title 登録手順
        .col-md-8.col-md-offset-2
          ul.center-block.lists
            li.center-block.lp-bottom_list 情報入力
            li.center-block.lp-bottom_list 入力内容確認
            li.center-block.lp-bottom_list 登録完了
        .col-md-6.col-md-offset-4
          ul.center-block.lists
            li.lp-top_list
              = link_to('会員登録', new_artist_registration_path, class: "btn btn-info fa-2x site-color")
            li.lp-top_list
              = link_to('ログイン', new_artist_session_path, class: "btn btn-info fa-2x site-color")
    = render "shared/footer"

app/views/top/index.html.slim
.row.center-block
  .col-md-8.pull-left
    .row
      .col-md-10.col-md-offset-2
        h2.new-q
         i(class="fa fa-question-circle-o fa-orange", aria-hidden="true")
         span.new-q--title 新着の質問
      - @questions.each do |q|
        .col-md-10.col-md-offset-2.q-content
          i(class="fa fa-question-circle-o fa-2x fa-orange", aria-hidden="true")
          = link_to("#{q.title}", question_path(q), class: "q-title")
          .col-md-12
            .q-text
              = q.text
            .q-answer
              i(class="fa fa-comment fa-lg fa-orange", aria-hidden="true")
              span.q-answers-count #{q.answers.count} 美容師回答
    .row
      .col-md-10.col-md-offset-2
        .panel.panel-info
          .panel-heading 美容師ランキング
          .panel-body
            | 回答数でランキングしています。
            span.artists-btn = link_to("美容師一覧", artists_path, class: "btn btn-info")
          ul.list-group
            - @artists.each_with_index do |artist, i|
              .list-group-item
                .media
                  a.media-left
                    .box
                  .media-body
                    h4.media-heading
                      span.artist-name #{i + 1} .
                      = link_to("#{artist.last_name} #{artist.first_name}", artist_path(artist.hash_id))
                    .artist-place
                    i(class="fa fa-map-marker fa-lg fa-orange", aria-hidden="true")
                    span.ml10 #{artist.prefecture.name}
                    .answer-count
                      i(class="fa fa-comment", aria-hidden="true")
                        span.ml10 回答数 #{artist.answers.count}
                    .artist-answer
                      .artist-answer_title 最近の投稿
                      .artist-answer_content
                        = artist.answers.last.text
          .panel-footer
            = link_to("美容師一覧", artists_path, class: "artists-index")
    .row
      .col-md-10.col-md-offset-2
        .panel.panel-info
          .panel-heading 役に立つ質問
          table.table
            tbody
              - @liked_questions.each_with_index do |l, i|
                tr
                  th #{i+1}
                  td #{l.text}
  .col-md-4.pull-right
    .col-md-12
      .faq
        h3.faq_title 美容専門のQAサービスです。
        p.faq_content 髪の専門家である美容師にあなたの疑問や悩みを相談しましょう。
        p
          a.btn.btn-info.btn-lg.center-block もっと詳しく
    .col-md-12
      .login-inv
        h3.login-inv_title
          span.label.label-info 新規登録/ログイン
        p.login-inv_content アカウントを作って、QAで質問しましょう。

app/views/top/index.slim
- @questions.each do |q|
  = q.title