config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :artists, controllers: {
    sessions:      'artists/sessions',
    passwords:     'artists/passwords',
    registrations: 'artists/registrations'
  }
  root to: "top#index"
  get "/explanation" => "top#explanation"
  resources :questions, path: "/questions", only: [:show, :new, :create]
  resources :answers, only: [:new, :create]
  resources :artists, param: :hash_id, path: "artists", only: [ :index, :show]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :answers
  belongs_to :prefecture
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :users
  has_many :artists
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :prefecture
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Jpmobile::ViewSelector
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation, :prefecture_id)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation, :header_photo)
    end
  end

end

app/controllers/artists/sessions_controller.rb
class Artists::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/artists/unlocks_controller.rb
class Artists::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    artist_ids = Answer.group(:artist_id).order('count_artist_id DESC').count(:artist_id).keys
    @artists = artist_ids.map{ |id| Artist.find(id) }
  end

  def show
    @artist = Artist.find_by(params[:hash_id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @related_questions = @question.category.questions.order(created_at: :desc).page(params[:page]).limit(5)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    unless @question.save
      render :new
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :text, :user_id, :category_id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).limit(5)
    artist_ids = Answer.group(:artist_id).order('count_artist_id DESC').limit(5).count(:artist_id).keys
    @artists = artist_ids.map{ |id| Artist.find(id) }
    @liked_questions = Question.order(want_count: :desc).limit(5)
  end

  def explanation
    render layout: false
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in


  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/quesitons_helper.rb
module QuesitonsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      | Hairabout
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "shared/header"
    .container-fluid
      = yield
    = render "shared/footer"

app/views/layouts/application_smart_phone.html.slim
doctype html
html
  head
    title
      | Hairabout
    = csrf_meta_tags
    = stylesheet_link_tag    'smart_phone/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "shared/header"
    = yield

app/views/shared/_footer.html.slim
footer.footer
  .navbar.navbar-default style="margin-bottom: 0px;"
    button.navbar-toggle data-target="#gnavi" data-toggle="collapse" type="button"
      span.icon-bar
      span.icon-bar
      span.icon-bar
    ul.nav.navbar-nav.nav-footer
      li.footer-list
        Hearaboutとは
      li.footer-list
        a 利用規約
      li.footer-list
        a 個人情報保護について
      li.footer-list
        a ヘルプ・お問い合わせ
      li.footer-list
        = link_to('会員登録', new_user_registration_path)
      li.footer-list
        = link_to('美容師の方はこちら', new_artist_registration_path)

app/views/shared/_header.html.slim
.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle data-target="#gnavi" data-toggle="collapse" type="button"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to("Hair About", root_path, class: "navbar-brand header-title")
    #gnavi.collapse.navbar-collapse
      - if user_signed_in?
        ul.nav.navbar-nav.navbar-right
          li.header-list
            = link_to('美容師の方はこちら', explanation_path ,class: "btn btn-info site-color")
          li.header-list
            = link_to('質問する', new_question_path, class: "btn btn-info site-color")
          li.header-list
            = link_to('ログアウト', destroy_user_session_path(current_user), :method => 'delete', class: "btn btn-info site-color")
      - else
        ul.nav.navbar-nav.navbar-right
          li.header-list
            = link_to('会員登録', new_user_registration_path, class: "btn btn-info site-color")
          li.header-list
            = link_to('美容師の方はこちら', explanation_path, class: "btn btn-info site-color")
          li.header-list
            = link_to('質問する', new_question_path, class: "btn btn-info site-color")

app/views/shared/_header_smart_phone.html.slim
.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle data-target="#gnavi" data-toggle="collapse" type="button"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to("Hair About", root_path, class: "navbar-brand header-title")
    #gnavi.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li.header-list
          = link_to('会員登録', new_user_registration_path, class: "btn btn-info")
        li.header-list
          = link_to('美容師の方はこちら', new_artist_registration_path, class: "btn btn-info")
        li.header-list
          = link_to('質問する', new_question_path, class: "btn btn-info")